### ISSUE TITLE
미승인 가맹점?

### ISSUE THREAD

**Issue by SINOTE** [hongsw/ajin-kcp-payment-woocommerce#14]
시험삼아 kcp플러그인으로 결제를 시도해 보았는데요, 프로그램이 설치되고 나서 kcp로 결제하기를 눌렀는데 미승인 가맹점이라면서 결제가 되지 않습니다.

왜 그런 건가요?

**Comment by hongsw** [comment]
예 미승인 가맹점이라는 것은
KCP 측에서 가맹점을 승인하지 않았다는 말입니다.

혹시 KCP측에서 전달된 Site Code 값과 Site Key를 정확히 입력하셨나요?


2014년 4월 10일 오후 2:58, SINOTE notifications@github.com님이 작성:

> 시험삼아 kcp플러그인으로 결제를 시도해 보았는데요, 프로그램이 설치되고 나서 kcp로 결제하기를 눌렀는데 미승인 가맹점이라면서
> 결제가 되지 않습니다.
> 
> 왜 그런 건가요?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/hongsw/ajin-kcp-payment-woocommerce/issues/14
> .

##

**Comment by hongsw** [comment]
KCP 에서 가입후 받으신 코드를(SITE CODE, SITE KEY) 우커머스 KCP 결제 플러그인 설정 페이지에서 입력하시면됩니다.

쉽게 설명드리기 위해서
아래 링크에서 <호스팅주소>을  해당 호스팅 주소로 변경후 페이지에 들어가시면

http://
<호스팅주소>/wp-admin/admin.php?page=wc-settings&tab=checkout&section=wc_gateway_kcp_card

플러그인의 설정에 site code와 site key를 입력하는 곳이 나옵니다.

입력후 맨 하단에 있는 저장버튼을 눌러주세요.

2014년 4월 10일 오후 3:58, SINOTE notifications@github.com님이 작성:

> KCP측에서는 개발자에게 사이트키와 코드를 알려줘서 연동을 시켜줘야 된다고 답변이 왔습니다.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/hongsw/ajin-kcp-payment-woocommerce/issues/14#issuecomment-40048490
> .

## 
\
